import { Logger } from '../lib/logger.js';

export function displayHelpText(): void {
  Logger.plain('');
  Logger.bold('SPREADSHEET MANAGEMENT COMMANDS:');
  Logger.plain('  $ sheet-cmd spreadsheet add              # Add a new spreadsheet (interactive)');
  Logger.plain('  $ sheet-cmd spreadsheet list             # List all spreadsheets (* = active)');
  Logger.plain('  $ sheet-cmd spreadsheet switch <name>    # Set active spreadsheet');
  Logger.plain('  $ sheet-cmd spreadsheet active           # Show currently active spreadsheet');
  Logger.plain('  $ sheet-cmd spreadsheet remove [name]    # Remove a spreadsheet');
  Logger.plain('');
  Logger.bold('SHEET OPERATIONS:');
  Logger.plain('  Sheet Management:');
  Logger.plain('  $ sheet-cmd sheet list-sheets              # List all sheets');
  Logger.plain('  $ sheet-cmd sheet add-sheet -n <name>      # Add a new sheet');
  Logger.plain('  $ sheet-cmd sheet remove-sheet -n <name>   # Remove a sheet');
  Logger.plain('  $ sheet-cmd sheet rename-sheet -n <old> --new-name <new>  # Rename a sheet');
  Logger.plain('  $ sheet-cmd sheet copy-sheet -n <name> --to <new> # Copy a sheet');
  Logger.plain('');
  Logger.plain('  Data Operations:');
  Logger.plain('  $ sheet-cmd sheet read-sheet -n <name>   # Read sheet content');
  Logger.plain('  $ sheet-cmd sheet write-cell -n <name> -c A1 -v "value"  # Write to cell');
  Logger.plain('  $ sheet-cmd sheet write-cell -n <name> -r A1:B2 -v "v1,v2;v3,v4"  # Write range');
  Logger.plain('  $ sheet-cmd sheet append-row -n <name> -v "val1,val2,val3"  # Append row');
  Logger.plain('');
  Logger.plain('  Import/Export:');
  Logger.plain('  $ sheet-cmd sheet import-csv -n <name> -f data.csv  # Import CSV');
  Logger.plain('  $ sheet-cmd sheet export -n <name> -f json  # Export to JSON/CSV');
  Logger.plain('');
  Logger.bold('UTILITY COMMANDS:');
  Logger.plain('  $ sheet-cmd update                       # Update to latest version');
  Logger.plain('  $ sheet-cmd completion install           # Install shell completion (zsh/bash)');
  Logger.plain('');
  Logger.bold('GETTING STARTED:');
  Logger.plain('  1. Get your service account credentials from Google Cloud Console');
  Logger.plain('     → Go to: https://console.cloud.google.com/');
  Logger.plain('     → Create a service account and download JSON credentials');
  Logger.plain('     → Share your Google Sheet with the service account email');
  Logger.plain('');
  Logger.plain('  2. Add your first spreadsheet:');
  Logger.plain('     → sheet-cmd spreadsheet add');
  Logger.plain('');
  Logger.plain('  3. Set it as active (so you don\'t need -s flag):');
  Logger.plain('     → sheet-cmd spreadsheet switch <name>');
  Logger.plain('');
  Logger.plain('  4. Start using sheet operations:');
  Logger.plain('     → sheet-cmd sheet list-sheets');
  Logger.plain('');
  Logger.dim('TIP: Use tab completion for easier navigation (sheet-cmd completion install)');
  Logger.plain('');
}
