import { GOOGLE_CLOUD_CONSOLE_URLS } from '../constants.js';
import { Logger } from '../lib/logger.js';

export function displayHelpText(): void {
  Logger.plain('');
  Logger.bold('ACCOUNT MANAGEMENT:');
  Logger.plain('  $ sheet-cmd account add                  # Add Google account via OAuth');
  Logger.plain('  $ sheet-cmd account list                 # List all accounts (* = active)');
  Logger.plain('  $ sheet-cmd account switch <email>       # Switch active account');
  Logger.plain('  $ sheet-cmd account remove <email>       # Remove account');
  Logger.plain('  $ sheet-cmd account reauth               # Re-authenticate active account');
  Logger.plain('');
  Logger.bold('SPREADSHEET MANAGEMENT:');
  Logger.plain('  $ sheet-cmd spreadsheet add                   # Add spreadsheet (interactive)');
  Logger.plain('  $ sheet-cmd spreadsheet add --id <id>         # Add spreadsheet by ID');
  Logger.plain('  $ sheet-cmd spreadsheet list                  # List spreadsheets (* = active)');
  Logger.plain('  $ sheet-cmd spreadsheet switch <name>         # Set active spreadsheet');
  Logger.plain('  $ sheet-cmd spreadsheet active                # Show currently active spreadsheet');
  Logger.plain('  $ sheet-cmd spreadsheet remove [name]         # Remove spreadsheet');
  Logger.plain('');
  Logger.bold('SHEET OPERATIONS:');
  Logger.plain('  Sheet Management:');
  Logger.plain('  $ sheet-cmd sheet list-sheets              # List all sheets');
  Logger.plain('  $ sheet-cmd sheet add-sheet -n <name>      # Add a new sheet');
  Logger.plain('  $ sheet-cmd sheet remove-sheet -n <name>   # Remove a sheet');
  Logger.plain('  $ sheet-cmd sheet rename-sheet -n <old> --new-name <new>  # Rename a sheet');
  Logger.plain('  $ sheet-cmd sheet copy-sheet -n <name> --to <new> # Copy a sheet');
  Logger.plain('');
  Logger.plain('  Data Operations:');
  Logger.plain('  $ sheet-cmd sheet read-sheet -n <name>   # Read sheet content');
  Logger.plain('  $ sheet-cmd sheet write-cell -n <name> -c A1 -v "value"  # Write to cell');
  Logger.plain('  $ sheet-cmd sheet write-cell -n <name> -r A1:B2 -v "v1,v2;v3,v4"  # Write range');
  Logger.plain('  $ sheet-cmd sheet append-row -n <name> -v "val1,val2,val3"  # Append row');
  Logger.plain('');
  Logger.plain('  Import/Export:');
  Logger.plain('  $ sheet-cmd sheet import-csv -n <name> -f data.csv  # Import CSV to sheet');
  Logger.plain('  $ sheet-cmd sheet export -n <name> -f json -o file.json  # Export to JSON/CSV');
  Logger.plain('');
  Logger.bold('UTILITY COMMANDS:');
  Logger.plain('  $ sheet-cmd update                       # Update to latest version');
  Logger.plain('  $ sheet-cmd completion install           # Install shell completion (zsh/bash)');
  Logger.plain('');
  Logger.bold('GETTING STARTED:');
  Logger.plain('  1. Setup Google Cloud Console:');
  Logger.plain(`     → Go to: ${GOOGLE_CLOUD_CONSOLE_URLS.CREDENTIALS}`);
  Logger.plain('     → Enable Google Sheets API');
  Logger.plain('     → Configure OAuth Consent Screen (External, add test users)');
  Logger.plain('     → Create OAuth 2.0 Client ID (Desktop app type)');
  Logger.plain('');
  Logger.plain('  2. Add your first account:');
  Logger.plain('     → sheet-cmd account add');
  Logger.plain('     → Enter Client ID and Secret from step 1');
  Logger.plain('     → Browser will open for authentication');
  Logger.plain('');
  Logger.plain('  3. Add a spreadsheet:');
  Logger.plain('     → sheet-cmd spreadsheet add');
  Logger.plain('');
  Logger.plain('  4. Start using sheet operations:');
  Logger.plain('     → sheet-cmd sheet list-sheets');
  Logger.plain('');
  Logger.dim('TIP: Use tab completion for easier navigation (sheet-cmd completion install)');
  Logger.plain('');
}
